# Generated by Django 4.1.4 on 2022-12-20 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taskstatusapp', '0001_initial'),
        ('categoryapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=500)),
                ('task_image', models.ImageField(upload_to='task_images')),
                ('needed_time', models.DateField()),
                ('task_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categoryapp.category')),
                ('task_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskstatusapp.taskstatus')),
            ],
        ),
    ]
