# Generated by Django 4.1.4 on 2022-12-21 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0003_alter_tasks_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='added_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tasks',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
