# Generated by Django 4.1.4 on 2022-12-22 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0004_tasks_added_date_tasks_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_todo', to='taskapp.tasks')),
            ],
        ),
    ]
