# Generated by Django 4.1.4 on 2022-12-23 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskstatusapp', '0004_alter_taskstatus_stat_color'),
        ('taskapp', '0005_todos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='task_status',
        ),
        migrations.AddField(
            model_name='todos',
            name='todo_note',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='todos',
            name='todo_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todo_stat_info', to='taskstatusapp.taskstatus'),
        ),
    ]
