# Generated by Django 4.1.4 on 2022-12-23 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0006_remove_tasks_task_status_todos_todo_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todos',
            name='todo_note',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
