# Generated by Django 4.1.4 on 2023-01-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0007_alter_todos_todo_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='todos',
            name='slug',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
