# Generated by Django 4.1.4 on 2022-12-30 09:52

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0007_alter_todos_todo_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='todos',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='todo_task.task_name', editable=False, populate_from='todo_task.task_name'),
        ),
    ]
