# Generated by Django 4.1.4 on 2022-12-20 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskstatusapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskstatus',
            name='stat_color',
            field=models.CharField(choices=[('blue', 'blue'), ('yellow', 'yellow'), ('green', 'green'), ('red', 'red'), ('grey', 'grey'), ('orange', 'orange'), ('pink', 'pink'), ('teal', 'teal'), ('black', 'black'), ('aqua', 'aqua')], max_length=20),
        ),
    ]
