# Generated by Django 4.1.4 on 2022-12-20 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=120)),
                ('cat_image', models.ImageField(upload_to='category_images')),
            ],
        ),
    ]
